parameters:
  # number of k3s nodes (default: 1)
  worker_count: 5

  # keypair for instances belongs to k3s cluster
  keypair: develop-key

  # external network name to get floating ip
  external_network: inside_provider

  # private network id for k3s cluster (if not specify, autocreated)
  private_network: inside

  # private subnet id for k3s cluster (if not specify, autocreated)
  private_subnet: inside

  # private subnet cidr for k3s cluster (default: 10.0.0.0/24)
  private_subnet_cidr:

  # image name for k3s server
  master_image: centos7

  # flavor name for k3s server
  master_flavor: g1.small

  # image name for k3s nodes
  worker_image: centos7

  # flavor name for k3s nodes
  worker_flavor: g1.small

  # network cidr for pods network (default: 10.42.0.0/16)
  pods_network_cidr:

  # disable agent on master node (default: no)
  disable_master_agent:

  # url to download k3s binary (default: https://github.com/rancher/k3s/releases/download/v0.1.0/k3s)
  k3s_binary_url:

  # username of rsync user to share node token (default: rsync_admin)
  node_token_share_user:

  # password of rsync user to share node token (default: password)
  node_token_share_secret:
