#!/bin/sh
cat <<EOF > /etc/heat_params
export K3S_BINARY_URL=${K3S_BINARY_URL}
export K3S_MASTER_PRIVATE_IP=${K3S_MASTER_PRIVATE_IP}
export K3S_MASTER_PUBLIC_IP=${K3S_MASTER_PUBLIC_IP}
export NODE_TOKEN_SHARE_USER=${NODE_TOKEN_SHARE_USER}
export NODE_TOKEN_SHARE_SECRET=${NODE_TOKEN_SHARE_SECRET}
EOF