#!/bin/sh
cat <<EOF > /etc/heat_params
export K3S_BINARY_URL=${K3S_BINARY_URL}
export K3S_MASTER_PUBLIC_IP=${K3S_MASTER_PUBLIC_IP}
export DISABLE_MASTER_AGENT=${DISABLE_MASTER_AGENT}
export PODS_NETWORK_CIDR=${PODS_NETWORK_CIDR}
export NODE_TOKEN_SHARE_USER=${NODE_TOKEN_SHARE_USER}
export NODE_TOKEN_SHARE_SECRET=${NODE_TOKEN_SHARE_SECRET}
EOF